image: node:latest

stages:
  - release

uat:
  type: deploy
  stage: release
  image: ruby:latest
  only:
    - uat
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_UAT_APP_NAME --api-key=$HEROKU_API_KEY_UAT

production:
  type: deploy
  stage: release
  image: ruby:latest
  only:
    - master
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY_PROD
